### ISSUE TITLE
wait-on hangs

### ISSUE THREAD

**Issue by MassMessage** [jeffbski/wait-on#116] opened 2022-02-16 21:21 UTC
I have a script like this:

 ```
 "scripts": {
    "start": "set PORT=3004 && react-scripts --openssl-legacy-provider start",
    "make": "electron-forge make",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "dev": "concurrently -k \"cross-env BROWSER=none npm start\" \"npm:electron\"",
    "electron": "wait-on tcp:3004 && electron ."
  }
```

running `yarn start` and `yarn electron` independly does work fine but running `yarn start`, waiting for the page to open then running in other shell: `yarn wait-on tcp:3004 && calc` hangs even albeit `http://localhost:3004` is opened in the browser (from the previous `yarn start` run). I didn't get any error. It just hangs. How can I fix that?

**Comment by TheRealLorenz** [comment] 2022-02-27 10:02
Could you paste the output of `yarn wait-on -v tcp:3004 && calc` ?

**Comment by MassMessage** [comment] 2022-03-02 03:33
> Could you paste the output of `yarn wait-on -v tcp:3004 && calc` ?

hangs too. What I eneded up doing was set the `HOST=127.0.0.1 PORT=3004` in .env file then `wait-on wait-on http://127.0.0.1:3004/` was back working.

**Comment by TheRealLorenz** [comment] 2022-03-02 17:58
> > Could you paste the output of `yarn wait-on -v tcp:3004 && calc` ?
> 
> hangs too. What I eneded up doing was set the `HOST=127.0.0.1 PORT=3004` in .env file then `wait-on wait-on http://127.0.0.1:3004/` was back working.

Yeah I solved it in the same way. This is a duplicate of #109 and #79

**Comment by MassMessage** [comment] 2022-03-03 03:59
> > > Could you paste the output of `yarn wait-on -v tcp:3004 && calc` ?
> > 
> > 
> > hangs too. What I eneded up doing was set the `HOST=127.0.0.1 PORT=3004` in .env file then `wait-on wait-on http://127.0.0.1:3004/` was back working.
> 
> Yeah I solved it in the same way. This is a duplicate of #109 and #79

sorry, I didn't find any of those before opening an issue. This one can be closed too

**Comment by TheCodeHeist** [comment] 2022-04-06 05:00
Oh wow,
I just solved it by replacing `wait-on http://localhost:3000/ && <NEXT_CMD>` with `wait-on http://127.0.0.1:3000/ && <NEXT_CMD>`, and nothing else was needed to do...

**Closed** 2022-04-06 16:51 UTC

**Comment by yuzhen1024** [comment] 2022-07-17 04:42
I `wait-on http://localhost:3000` hangs, but `wait-on http://127.0.0.1:3000` is fine.
